# Generated by Django 6.0.6 on 2026-08-07 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_cart_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_kn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
