# Generated by Django 6.0.6 on 2026-08-12 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_cartitem_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
