# Generated by Django 6.0.6 on 2026-08-13 13:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_payment'),
    ]

    operations = [
    ]
