# Generated by Django 6.0.6 on 2026-08-13 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_alter_order_id'),
    ]

    operations = [
    ]
