# Generated by Django 6.0.6 on 2026-08-14 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_order_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='orderid',
            new_name='razorpay_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='payment_id',
            new_name='razorpay_payment_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='signature',
            new_name='razorpay_signature',
        ),
    ]
