# Generated by Django 6.0.6 on 2026-08-16 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0025_alter_payment_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_order_id',
            new_name='cashfree_order_id',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='razorpay_payment_id',
            new_name='cashfree_payment_id',
        ),
    ]
