# Generated by Django 6.0.6 on 2026-08-16 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0026_rename_razorpay_order_id_payment_cashfree_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('CREATED', 'Created'), ('SUCCESS', 'Success'), ('FAILED', 'Failed'), ('PENDING', 'Pending')], default='CREATED', max_length=100),
        ),
    ]
