# Generated by Django 6.0.6 on 2026-08-19 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PENDING', 'pending'), ('PAID', 'paid'), ('SHIPPED', 'shipped'), ('DELIVERED', 'delivered'), ('CANCELED', 'canceled')], default='PENDING', max_length=10),
        ),
    ]
