# Generated by Django 6.0.6 on 2026-08-21 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0028_alter_order_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
